services:
  # Backend API Service
  - type: web
    name: enotes-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: enotes-frontend
    env: static
    buildCommand: cd frontend/notes-app && npm install && npm run build
    staticPublishPath: frontend/notes-app/build